Update: doc for Heading and TextContainer
qikify/polaris-vue pull request #102
Opened 2022-02-17 10:47 UTC by HQCuong

2022-02-17 11:02 UTC, blacklen approved these changes

2022-02-18 10:16 UTC, juzser requested changes

2022-02-18 10:16 UTC, juzser commented on src/components/TextContainer/README.stories.mdx
> +  title="Components / Titles and text / TextContainer"
`Text Container` missing space

2022-02-18 10:16 UTC, juzser commented on src/components/TextContainer/README.stories.mdx
> +export const Template = (args, { argTypes }) => ({
Only need this, don't need other story

2022-03-02 10:08 UTC, merged